workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.elkom.activereminder"
      node: 20.10.0
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Expo Prebuild
        script: |
          npx expo prebuild --platform android

      - name: Build Android Release
        script: |
          keytool -genkey -v -keystore /tmp/keystore.keystore \
            -alias active-reminder-alias \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass password123 -keypass password123 \
            -dname "CN=Active Reminder,O=Elkom,C=US"

          cd android
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=/tmp/keystore.keystore \
            -Pandroid.injected.signing.store.password=password123 \
            -Pandroid.injected.signing.key.alias=active-reminder-alias \
            -Pandroid.injected.signing.key.password=password123
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - ahmedelkoumey@gmail.com

  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      node: 20.10.0
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm install

      - name: Expo Prebuild
        script: npx expo prebuild --platform ios

      - name: Install CocoaPods
        script: cd ios && pod install

      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --workspace "ios/ActiveReminder.xcworkspace" \
            --scheme "ActiveReminder"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - ahmedelkoumey@gmail.com
